# Copyright 2020 Changkun Ou. All rights reserved.

version: '3'

services:
  research:
    build: .
    restart: always
    image: research:latest
    environment:
      - "RESEARCH_ADDR=research:80"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external: true